# Generated by Django 3.2.7 on 2021-09-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210917_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport_in',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_out',
        ),
    ]
