# Generated by Django 3.2.7 on 2021-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210919_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
