# Generated by Django 3.2.7 on 2021-09-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySklad',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
                ('CountrySklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklad', to='sklad.countrysklad')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sklad')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklad', to='sklad.sklad')),
            ],
        ),
    ]
