# Generated by Django 3.2.7 on 2021-09-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='sklads'),
        ),
        migrations.AlterField(
            model_name='image',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklads', to='sklad.sklad'),
        ),
        migrations.AlterField(
            model_name='sklad',
            name='CountrySklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sklads', to='sklad.countrysklad'),
        ),
    ]
