# Generated by Django 3.2.7 on 2021-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210917_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='date',
            field=models.DateField(default='19.09.2021'),
        ),
    ]
