# Generated by Django 3.2.7 on 2021-09-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_parcels_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='date',
            field=models.DateField(default='21.09.2021'),
        ),
    ]
